#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "../lib/probability.h"



/*
 * Poisson Distribution.
 * p[k] = exp(- L) * (L^k / k!)
 *
 */
int main(int argc, const char *argv[])
{

    double pk;



    int nk = 50; // k values
    int nLambda = 20; // lambda values

    double *lambda = (double *)malloc(nLambda * sizeof(double));
    double *pklist = (double *)malloc(nLambda * nk * sizeof(double));

    // initialize lambda values
    for (int i = 0; i < nLambda; i++) {
        *(lambda + i) = i + 1;
    }


    // calculate the poisson PMF
    for(int indexLambda = 0; indexLambda < nLambda; indexLambda++) { // calculte for all lambda values
        for(int indexK = 0; indexK < nk; indexK++) { // calculate all k values for given lambda
            pk = exp(- *(lambda + indexLambda)) * (pow(*(lambda + indexLambda), indexK) / factorial(indexK));
            printf(" %.10lf ", pk);
            *(pklist + (indexK * nLambda) + indexLambda) = pk;
        }
        printf("\n");
    }


    // printf("# Data generated by poisson PMF \n");
    // printf("# p[k] = exp(-lambda) * (lambda^(k) / k!)\n");
    // printf("# k values are [1..%d]\n", nk);
    // printf("# lambda values are [1..%d]\n", nLambda);
    // printf("# Each indexK represent PMF value for all k values, starting with lambda value\n");
    // printf("###########################################################################\n");
    // for(int indexLambda = 0; indexLambda < nLambda; indexLambda++) {
    //     printf("%.1lf", *(lambda + indexLambda));
    //     for(int indexK = 0; indexK < nk; indexK++) {
    //         printf(" %.10lf ", *(pklist + (indexK * nLambda) + indexLambda));
    //     }
    //     printf("\n");
    // }


    return 0;
}











/*

                k = 1   k = 2   k = 3   k = 4 ...... k = 50
lambda = 1      xxxx    xxxx    xxxx    xxxx         xxxxx
lambda = 2      xxxx                                 xxxxx
    .
    .
    .
lambda = 20     xxxx            ...                  xxxxx

*/
